export const INCREMENT ='INCREMENT';
export const DECREMENT ='DECREMENT';
export const CAU_CHAO ='CAU_CHAO';

export const DOC_DANH_SACH_NGUOI_DUNG ='DOC_DANH_SACH_NGUOI_DUNG';
export const DOC_DANH_SACH_NGUOI_DUNG_THANH_CONG ='DOC_DANH_SACH_NGUOI_DUNG_THANH_CONG';
export const DOC_DANH_SACH_NGUOI_DUNG_THAT_BAI ='DOC_DANH_SACH_NGUOI_DUNG_THAT_BAI';